export const MY_LIST_LOAD_REQUEST = 'MY_LIST_LOAD_REQUEST';
export const MY_LIST_LOAD_SUCCESS = 'MY_LIST_LOAD_SUCCESS';
export const MY_LIST_LOAD_FAILURE = 'MY_LIST_LOAD_FAILURE';

export const MY_LIST_ADD_ITEM = 'MY_LIST_ADD_ITEM';
