export const MY_LIST_LOAD_REQUEST = 'MY_LIST_LOAD_REQUEST';
export const MY_LIST_LOAD_SUCCESS = 'MY_LIST_LOAD_SUCCESS';
export const MY_LIST_LOAD_FAILURE = 'MY_LIST_LOAD_FAILURE';

export const MY_LIST_ADD_ITEM_REQUEST = 'MY_LIST_ADD_ITEM_REQUEST';
export const MY_LIST_ADD_ITEM_SUCCESS = 'MY_LIST_ADD_ITEM_SUCCESS';
export const MY_LIST_ADD_ITEM_FAILURE = 'MY_LIST_ADD_ITEM_FAILURE';

export const MY_LIST_UPDATE_ITEM_REQUEST = 'MY_LIST_UPDATE_ITEM_REQUEST';
export const MY_LIST_UPDATE_ITEM_SUCCESS = 'MY_LIST_UPDATE_ITEM_SUCCESS';
export const MY_LIST_UPDATE_ITEM_FAILURE = 'MY_LIST_UPDATE_ITEM_FAILURE';

export const MY_GROUPS_LOAD_REQUEST = 'MY_GROUPS_LOAD_REQUEST';
export const MY_GROUPS_LOAD_SUCCESS = 'MY_GROUPS_LOAD_SUCCESS';
export const MY_GROUPS_LOAD_FAILURE = 'MY_GROUPS_LOAD_FAILURE';

export const MY_GROUPS_CREATE_REQUEST = 'MY_GROUPS_CREATE_REQUEST';
export const MY_GROUPS_CREATE_SUCCESS = 'MY_GROUPS_CREATE_SUCCESS';
export const MY_GROUPS_CREATE_FAILURE = 'MY_GROUPS_CREATE_FAILURE';

export const MY_GROUPS_UPDATE_REQUEST = 'MY_GROUPS_UPDATE_REQUEST';
export const MY_GROUPS_UPDATE_SUCCESS = 'MY_GROUPS_UPDATE_SUCCESS';
export const MY_GROUPS_UPDATE_FAILURE = 'MY_GROUPS_UPDATE_FAILURE';
