export const ACCOUNT_CREATE_REQUEST = 'ACCOUNT_CREATE_REQUEST';
export const ACCOUNT_CREATE_SUCCESS = 'ACCOUNT_CREATE_SUCCESS';
export const ACCOUNT_CREATE_FAILURE = 'ACCOUNT_CREATE_FAILURE';

export const INVITATION_LOAD_REQUEST = 'INVITATION_LOAD_REQUEST';
export const INVITATION_LOAD_SUCCESS = 'INVITATION_LOAD_SUCCESS';
export const INVITATION_LOAD_FAILURE = 'INVITATION_LOAD_FAILURE';

export const MY_LIST_LOAD_REQUEST = 'MY_LIST_LOAD_REQUEST';
export const MY_LIST_LOAD_SUCCESS = 'MY_LIST_LOAD_SUCCESS';
export const MY_LIST_LOAD_FAILURE = 'MY_LIST_LOAD_FAILURE';

export const MY_LIST_ADD_ITEM_REQUEST = 'MY_LIST_ADD_ITEM_REQUEST';
export const MY_LIST_ADD_ITEM_SUCCESS = 'MY_LIST_ADD_ITEM_SUCCESS';
export const MY_LIST_ADD_ITEM_FAILURE = 'MY_LIST_ADD_ITEM_FAILURE';

export const MY_LIST_UPDATE_ITEM_REQUEST = 'MY_LIST_UPDATE_ITEM_REQUEST';
export const MY_LIST_UPDATE_ITEM_SUCCESS = 'MY_LIST_UPDATE_ITEM_SUCCESS';
export const MY_LIST_UPDATE_ITEM_FAILURE = 'MY_LIST_UPDATE_ITEM_FAILURE';

export const MY_GROUPS_LOAD_ALL_REQUEST = 'MY_GROUPS_LOAD_ALL_REQUEST';
export const MY_GROUPS_LOAD_ALL_SUCCESS = 'MY_GROUPS_LOAD_ALL_SUCCESS';
export const MY_GROUPS_LOAD_ALL_FAILURE = 'MY_GROUPS_LOAD_ALL_FAILURE';

export const MY_GROUPS_LOAD_REQUEST = 'MY_GROUPS_LOAD_REQUEST';
export const MY_GROUPS_LOAD_SUCCESS = 'MY_GROUPS_LOAD_SUCCESS';
export const MY_GROUPS_LOAD_FAILURE = 'MY_GROUPS_LOAD_FAILURE';

export const MY_GROUPS_CREATE_REQUEST = 'MY_GROUPS_CREATE_REQUEST';
export const MY_GROUPS_CREATE_SUCCESS = 'MY_GROUPS_CREATE_SUCCESS';
export const MY_GROUPS_CREATE_FAILURE = 'MY_GROUPS_CREATE_FAILURE';

export const MY_GROUPS_UPDATE_REQUEST = 'MY_GROUPS_UPDATE_REQUEST';
export const MY_GROUPS_UPDATE_SUCCESS = 'MY_GROUPS_UPDATE_SUCCESS';
export const MY_GROUPS_UPDATE_FAILURE = 'MY_GROUPS_UPDATE_FAILURE';


export const SESSION_CREATE_REQUEST = 'SESSION_CREATE_REQUEST';
export const SESSION_CREATE_SUCCESS = 'SESSION_CREATE_SUCCESS';
export const SESSION_CREATE_FAILURE = 'SESSION_CREATE_FAILURE';

export const SESSION_DESTROY_REQUEST = 'SESSION_DESTROY_REQUEST';
export const SESSION_DESTROY_SUCCESS = 'SESSION_DESTROY_SUCCESS';
export const SESSION_DESTROY_FAILURE = 'SESSION_DESTROY_FAILURE';
